
M = {}

local font_names = {
  "3-d.flf",
  "3x5.flf",
  "5lineoblique.flf",
  "acrobatic.flf",
  "alligator.flf",
  "alligator2.flf",
  "alphabet.flf",
  "avatar.flf",
  "banner.flf",
  "banner3-D.flf",
  "banner3.flf",
  "banner4.flf",
  "barbwire.flf",
  "basic.flf",
  "bell.flf",
  "big.flf",
  "bigchief.flf",
  "binary.flf",
  "block.flf",
  "broadway.flf",
  "bubble.flf",
  "bulbhead.flf",
  "calgphy2.flf",
  "caligraphy.flf",
  "catwalk.flf",
  "chunky.flf",
  "coinstak.flf",
  "colossal.flf",
  "computer.flf",
  "contessa.flf",
  "contrast.flf",
  "cosmic.flf",
  "cosmike.flf",
  "crawford.flf",
  "cricket.flf",
  "cursive.flf",
  "cyberlarge.flf",
  "cybermedium.flf",
  "cybersmall.flf",
  "decimal.flf",
  "diamond.flf",
  "digital.flf",
  "doh.flf",
  "doom.flf",
  "dotmatrix.flf",
  "double.flf",
  "drpepper.flf",
  "dwhistled.flf",
  "eftichess.flf",
  "eftifont.flf",
  "eftipiti.flf",
  "eftirobot.flf",
  "eftitalic.flf",
  "eftiwall.flf",
  "eftiwater.flf",
  "epic.flf",
  "fender.flf",
  "fourtops.flf",
  "fraktur.flf",
  "fuzzy.flf",
  "goofy.flf",
  "gothic.flf",
  "graceful.flf",
  "gradient.flf",
  "graffiti.flf",
  "hex.flf",
  "hollywood.flf",
  "invita.flf",
  "isometric1.flf",
  "isometric2.flf",
  "isometric3.flf",
  "isometric4.flf",
  "italic.flf",
  "ivrit.flf",
  "jazmine.flf",
  "jerusalem.flf",
  "katakana.flf",
  "kban.flf",
  "l4me.flf",
  "larry3d.flf",
  "lcd.flf",
  "lean.flf",
  "letters.flf",
  "linux.flf",
  "lockergnome.flf",
  "madrid.flf",
  "marquee.flf",
  "maxfour.flf",
  "mike.flf",
  "mini.flf",
  "mirror.flf",
  "mnemonic.flf",
  "morse.flf",
  "moscow.flf",
  "mshebrew210.flf",
  "nancyj-fancy.flf",
  "nancyj-underlined.flf",
  "nancyj.flf",
  "nipples.flf",
  "ntgreek.flf",
  "nvscript.flf",
  "o8.flf",
  "octal.flf",
  "ogre.flf",
  "os2.flf",
  "pawp.flf",
  "peaks.flf",
  "pebbles.flf",
  "pepper.flf",
  "poison.flf",
  "puffy.flf",
  "pyramid.flf",
  "rectangles.flf",
  "relief.flf",
  "relief2.flf",
  "rev.flf",
  "roman.flf",
  "rot13.flf",
  "rounded.flf",
  "rowancap.flf",
  "rozzo.flf",
  "runic.flf",
  "runyc.flf",
  "sblood.flf",
  "script.flf",
  "serifcap.flf",
  "shadow.flf",
  "short.flf",
  "slant.flf",
  "slide.flf",
  "slscript.flf",
  "small.flf",
  "smisome1.flf",
  "smkeyboard.flf",
  "smscript.flf",
  "smshadow.flf",
  "smslant.flf",
  "smtengwar.flf",
  "speed.flf",
  "stacey.flf",
  "stampatello.flf",
  "standard.flf",
  "starwars.flf",
  "stellar.flf",
  "stop.flf",
  "straight.flf",
  "tanja.flf",
  "tengwar.flf",
  "term.flf",
  "thick.flf",
  "thin.flf",
  "threepoint.flf",
  "ticks.flf",
  "ticksslant.flf",
  "tinker-toy.flf",
  "tombstone.flf",
  "trek.flf",
  "tsalagi.flf",
  "twopoint.flf",
  "univers.flf",
  "usaflag.flf",
  "weird.flf",
  "whimsy.flf",
}

function M.asciify(text)
  local chosen_font = font_names[math.random(#font_names)]
  local handle = io.popen("figlet -f " .. chosen_font .. " " .. text)

  if handle == nil then
    return
  end

  local result = handle:read("*a")
  print("Chosen Font: " .. chosen_font)

  return result
end


return M
